import { useCallback, useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { isTauri } from '@/utils/tauri';

export type TagMergeStrategy = 'union' | 'user-only' | 'ai-only' | 'disabled';

const STORAGE_KEY = 'tag_merge_strategy';
const DEFAULT_STRATEGY: TagMergeStrategy = 'union';

/**
 * Merge tags based on the selected strategy
 * @param userTags - Tags extracted from rich content (user input)
 * @param aiTags - Tags generated by AI
 * @param strategy - The merge strategy to use
 * @returns Merged tags array
 */
export const mergeTagsByStrategy = (
  userTags: string[],
  aiTags: string[],
  strategy: TagMergeStrategy
): string[] => {
  switch (strategy) {
    case 'union':
      // Combine all tags, remove duplicates
      return Array.from(new Set([...userTags, ...aiTags]));

    case 'user-only':
      // Only keep user-input tags, fallback to AI if user has none
      return userTags.length > 0 ? userTags : aiTags;

    case 'ai-only':
      // Only use AI-generated tags, fallback to user if AI has none
      return aiTags.length > 0 ? aiTags : userTags;

    case 'disabled':
      // Disable AI tag generation completely, only use user tags
      return userTags;

    default:
      // Fallback to union
      return Array.from(new Set([...userTags, ...aiTags]));
  }
};

/**
 * Hook to manage tag merge strategy settings
 */
export const useTagMergeStrategy = () => {
  const [strategy, setStrategy] = useState<TagMergeStrategy>(DEFAULT_STRATEGY);
  const [isLoading, setIsLoading] = useState(true);

  // Load strategy from storage
  const loadStrategy = useCallback(async () => {
    setIsLoading(true);
    try {
      if (isTauri()) {
        const loaded = await invoke<string>('get_tag_merge_strategy');
        setStrategy(loaded as TagMergeStrategy);
      } else {
        // Fallback to localStorage for web
        const saved = localStorage.getItem(STORAGE_KEY);
        if (saved) {
          setStrategy(saved as TagMergeStrategy);
        }
      }
    } catch (error) {
      console.error('Failed to load tag merge strategy:', error);
      // Use default on error
      setStrategy(DEFAULT_STRATEGY);
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Save strategy to storage
  const saveStrategy = useCallback(async (newStrategy: TagMergeStrategy) => {
    try {
      if (isTauri()) {
        await invoke('save_tag_merge_strategy', { strategy: newStrategy });
      } else {
        // Fallback to localStorage for web
        localStorage.setItem(STORAGE_KEY, newStrategy);
      }
      setStrategy(newStrategy);
    } catch (error) {
      console.error('Failed to save tag merge strategy:', error);
      throw error;
    }
  }, []);

  // Load strategy on mount and listen for changes
  useEffect(() => {
    loadStrategy();

    if (isTauri()) {
      // Listen for cross-window sync events
      const unlistenPromise = listen<string>('tag-merge-strategy-changed', (event) => {
        setStrategy(event.payload as TagMergeStrategy);
      });

      return () => {
        unlistenPromise.then((unlisten) => unlisten());
      };
    }
  }, [loadStrategy]);

  return {
    strategy,
    saveStrategy,
    isLoading,
    mergeTagsByStrategy: (userTags: string[], aiTags: string[]) =>
      mergeTagsByStrategy(userTags, aiTags, strategy),
  };
};
