/**
 * Utility for extracting note titles with intelligent priority logic
 *
 * Priority order:
 * 1. User manual edit (handled separately via manualTitle flag)
 * 2. AI auto-generation (future feature)
 * 3. First H1 heading (markdown # or richContent heading)
 * 4. First sentence (plain text fallback)
 */

interface HeadingNode {
  type?: string;
  children?: Array<{ text?: string; type?: string; children?: any[] }>;
}

/**
 * Extract heading text from richContent (Plate.js format)
 */
const extractHeadingFromRichContent = (richContent: any): string | null => {
  if (!richContent || !Array.isArray(richContent)) {
    return null;
  }

  // Find first h1 node in richContent
  for (const node of richContent) {
    if (node.type === 'h1' && Array.isArray(node.children)) {
      // Extract text from all text children
      const text = node.children
        .filter((child: any) => child.text !== undefined)
        .map((child: any) => child.text)
        .join('')
        .trim();

      if (text) {
        return text;
      }
    }
  }

  return null;
};

/**
 * Extract heading from markdown text (handles # ## ### etc.)
 */
const extractHeadingFromMarkdown = (text: string): string | null => {
  if (!text) {
    return null;
  }

  const lines = text.split('\n');
  const firstLine = lines[0]?.trim();

  if (!firstLine) {
    return null;
  }

  // Match markdown headings: # Title, ## Title, ### Title, etc.
  const headingMatch = firstLine.match(/^#{1,6}\s+(.+)$/);

  if (headingMatch && headingMatch[1]) {
    return headingMatch[1].trim();
  }

  return null;
};

/**
 * Extract first sentence from plain text
 * Handles various sentence endings and truncates to maxLength
 */
const extractFirstSentence = (text: string, maxLength: number = 50): string | null => {
  if (!text) {
    return null;
  }

  // Remove leading/trailing whitespace and normalize line breaks
  const normalized = text.trim().replace(/\n/g, ' ');

  if (!normalized) {
    return null;
  }

  // Try to find first sentence (ending with . ! ? or newline in original)
  const sentenceMatch = normalized.match(/^[^.!?]+[.!?]/);

  if (sentenceMatch) {
    const sentence = sentenceMatch[0].trim();
    return sentence.length > maxLength
      ? sentence.substring(0, maxLength)
      : sentence;
  }

  // No sentence ending found, just take first N characters
  return normalized.length > maxLength
    ? normalized.substring(0, maxLength)
    : normalized;
};

export interface ExtractTitleOptions {
  text: string;
  richContent?: any;
  maxLength?: number;
  fallback?: string;
}

/**
 * Extract note title with intelligent priority logic
 *
 * @param options.text - Plain text content
 * @param options.richContent - Rich content (Plate.js format)
 * @param options.maxLength - Maximum title length (default: 50)
 * @param options.fallback - Fallback title if extraction fails (default: 'Untitled Note')
 * @returns Extracted title string
 */
export const extractNoteTitle = ({
  text,
  richContent,
  maxLength = 50,
  fallback = 'Untitled Note'
}: ExtractTitleOptions): string => {
  // Priority 1: Check richContent for H1 heading
  const richHeading = extractHeadingFromRichContent(richContent);
  if (richHeading) {
    return richHeading.length > maxLength
      ? richHeading.substring(0, maxLength)
      : richHeading;
  }

  // Priority 2: Check markdown text for # heading
  const markdownHeading = extractHeadingFromMarkdown(text);
  if (markdownHeading) {
    return markdownHeading.length > maxLength
      ? markdownHeading.substring(0, maxLength)
      : markdownHeading;
  }

  // Priority 3: Extract first sentence
  const firstSentence = extractFirstSentence(text, maxLength);
  if (firstSentence) {
    return firstSentence;
  }

  // Fallback
  return fallback;
};

/**
 * Check if a title was likely auto-generated (vs manually edited)
 * Used to determine if title should be regenerated on content change
 */
export const isAutoGeneratedTitle = (title: string, text: string, richContent?: any): boolean => {
  if (!title || !text) {
    return false;
  }

  // Check if title matches current auto-extraction result
  const autoTitle = extractNoteTitle({ text, richContent, fallback: '' });

  // Exact match or prefix match (due to length truncation)
  return title === autoTitle || autoTitle.startsWith(title) || title.startsWith(autoTitle);
};
